### ISSUE TITLE
Image in Layouts can't be added or selected (3.6 rc4)

### ISSUE THREAD

**Issue by lexislav** [k-next/kirby#3924]
**Describe the bug**  
Image field inside Layouts can't be edit now - clicking the add button opens the dropwdown (select, upload) but both choices do nothing.

**To Reproduce**  
Add image to layout. Click on image to edit image field. Click add image - try to upload or select…

**Expected behavior**  
Click on select/change image in panel opens the dialog to do the action.

**Kirby Version**  
Kirby 3.6 r.c.4

**Desktop (please complete the following information):**  
 - OS: macOS Monterey
 - Browser: Safari 15.1, Chrome

**Comment by afbora** [comment]
Is this a safari specific bug? 🤔 I couldn't reproduce the issue on Chrome 95 & Firefox 93 & Windows 10.

**Comment by afbora** [comment]
@lexislav Is there any output on console?

**Comment by lexislav** [comment]
I have tried on macOS with Chrome and Firefox - the same. This dropdown doesn¨t work:

But no error on console.

When existing image is removed from field, clicking on filed shows this error - this.$refs.options.toggle is not a function:


This is also shown on console:

index.js:1 TypeError: this.$refs.options.toggle is not a function
    at a.prompt (index.js:1)
    at Vt (vendor.js:6)
    at HTMLButtonElement.n (vendor.js:6)
    at HTMLButtonElement.i._wrapper (vendor.js:6)

**Comment by bastianallgeier** [comment]
Hm, I just tried and I'm also not able to reproduce this at all. This is weird.

**Comment by lexislav** [comment]
The bug was not on the fresh install, but on a site I have tried to update from Kirby 3.5.7.

After transfering all site's blueprints, content, configs to the fresh install of rc4, the issues is gone.
So that is wierd indeed.

**Comment by bastianallgeier** [comment]
Maybe something got messed up in the cache. I think we will never know :) Thanks for taking the time to upgrade everything!

**Comment by zakgreene** [comment]
I'm having the same issue after upgrading from 3.5.4 via composer, can't select or upload images across the site. Same errors, `this.$refs.options.toggle is not a function` when clicking any image field, same output to console from `index.js`.

**Comment by zakgreene** [comment]
Tried a fresh install, uploading worked until I copied my project files (content, templates, blueprints, controllers, languages, plugins). I disabled plugins, disabled languages, and uploading on a Files section worked when I disabled languages, but not as part of a layout image subfield. Looks like I'll have to downgrade unfortunately.

**Comment by afbora** [comment]
@zakgreene Do you have a chance to share your project with us as you got the error to close look? To e-mail: support@getkirby.com

**Comment by thisissasa** [comment]
has also happend for me after upgrading to kirby 3.6.2. It seems to be triggered by the retour plugin (3.0.0)
